name: Docker image CI

on:
  push:
    tags:
      - "v*"

jobs:
  build-sorting-server:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - name: Build and push sorting server
        run: |
          echo "${{secrets.PASSWORD}}" | docker login -u "suhail12" --password-stdin
          docker image build -t suhail12/sorting-server:stable-latest .
          docker tag suhail12/sorting-server:stable-latest suhail12/sorting-server:stable-${GITHUB_REF/refs\/tags\//}
          docker tag suhail12/sorting-server:stable-latest suhail12/sorting-server:stable-${GITHUB_SHA::8}
          docker push suhail12/sorting-server:stable-latest
          docker push suhail12/sorting-server:stable-${GITHUB_REF/refs\/tags\//}
          docker push suhail12/sorting-server:stable-${GITHUB_SHA::8}
